// assets_test.go
package regis_test

import (
	"bytes"
	"testing"

	regis "git.disroot.org/jmy/regis"
)

func TestAIContext_NonEmpty(t *testing.T) {
	if len(regis.AIContext) == 0 {
		t.Fatal("AIContext is empty — embed may have failed")
	}
}

func TestAIContext_ContainsSchemaReference(t *testing.T) {
	if !bytes.Contains(regis.AIContext, []byte("Schema Reference")) {
		t.Error("AIContext missing 'Schema Reference' section")
	}
}

func TestAIContext_NotAutoGeneratedWarningVisible(t *testing.T) {
	if !bytes.Contains(regis.AIContext, []byte("auto-generated")) {
		t.Error("AIContext missing auto-generated header")
	}
}
