// assets_test.go
package regis_test

import (
	"bytes"
	"testing"

	regis "git.disroot.org/jmy/regis"
)

func TestRTFContext_NonEmpty(t *testing.T) {
	if len(regis.RTFContext) == 0 {
		t.Fatal("RTFContext is empty — embed may have failed")
	}
}

func TestRTFContext_ContainsSchemaReference(t *testing.T) {
	if !bytes.Contains(regis.RTFContext, []byte("Schema Reference")) {
		t.Error("RTFContext missing 'Schema Reference' section")
	}
}

func TestRTFContext_NotAutoGeneratedWarningVisible(t *testing.T) {
	if !bytes.Contains(regis.RTFContext, []byte("auto-generated")) {
		t.Error("RTFContext missing auto-generated header")
	}
}
