// cmd/regis-docgen/main.go

// Generates docs/regis-ai-context.md entirely from source code annotations.

// Run from the repo root: go run ./cmd/regis-docgen



package main



import (

	"bytes"

	"fmt"

	"go/ast"

	"go/parser"

	"go/token"

	"os"

	"path/filepath"

	"reflect"

	"sort"

	"strings"

	"unicode"

)



const (

	defaultTypesFile    = "internal/config/types.go"

	defaultInterpolFile = "internal/config/interpolate.go"

	defaultCueDir       = "internal/cue"

	defaultCobraDir     = "cmd/regis/cmd"

	defaultContextFile  = "docs/regis-ai-context.md"

	defaultSchemaFile   = "docs/regis-schema.yaml"

	defaultExampleFile  = "cmd/regis-docgen/example.yml"

)



// defaults maps "StructName.FieldName" -> default value string for the table.

var defaults = map[string]string{

	"Target.Port":           "22",

	"Target.Sudo":           "false",

	"RunConfig.Mode":        "sequential",

	"RunConfig.OnFailure":   "halt",

	"RunConfig.SuccessWhen": "auto",

	"RunConfig.OnError":     "halt",

	"StateConfig.Enabled":  "true",

	"StateConfig.LocalDir": ".regis-states",

	"StateConfig.Keep":    "5",

	"ConcurrencyConfig.Lock":     "true",

	"ConcurrencyConfig.OnLocked": "fail",

	"ConcurrencyConfig.LockWait": "30s",

	"CueRef.DiffMode": "binary",

}



// fieldInfo holds parsed info about a struct field.

type fieldInfo struct {

	yamlKey string

	goType  string

	doc     string

	def     string // default value, if any

}



// natureEntry holds a parsed doc:nature block.

type natureEntry struct {

	name  string

	lines []string

}



const docgenHeader = `<!-- This file is auto-generated by cmd/regis-docgen. Do not edit manually. -->

# regis AI Context



` + "`regis`" + ` is a single Go binary that reads ` + "`regis.yml`" + ` and deploys over SSH — no daemon, no agent on target. It uploads binaries, syncs config files, merges secrets, and runs commands, driven by a single YAML file.



---



`



const sectionKeyConceptsBody = `

### requires / needs



` + "`requires: [scenario-a, scenario-b]`" + ` declares prerequisites — scenarios that must complete before this one starts. Prerequisites are **deduplicated**: if multiple scenarios all require ` + "`build`" + `, it runs exactly once. ` + "`needs:`" + ` is an accepted alias.

Each scenario in ` + "`requires:`" + ` is **independent**: it runs as its own unit with its own ` + "`on_error`" + ` policy. A failure in a prerequisite does **not** trigger the dependent scenario's ` + "`on_error: restore`" + `. Use inline scenario refs (` + "`{ scenario: x }`" + ` in ` + "`cues:`" + `) when you need the parent's ` + "`on_error`" + ` to cover the referenced scenario's cues.



### Post-action deduplication



Post-actions from all changed cues are collected, deduplicated by command string, then executed once. Five cues all declaring ` + "`post: reload:nginx`" + ` result in exactly one nginx reload. Same command + different ` + "`sudo:`" + ` values → ` + "`sudo: true`" + ` wins.



### Scenario-level post



A ` + "`post:`" + ` field on a scenario fires once if **any remote cue** in the scenario changed — regardless of which ones. Local cues (` + "`local: true`" + `) never trigger it.



` + "```yaml\nSaver:\n  post: restart:saver   # runs once if env or bin changed; skipped if only local build changed\n  cues:\n    - { name: build, nature: action, local: true, cmd: go build … }\n    - { name: env,   nature: secret, … }   # changing this triggers the post\n    - { name: bin,   nature: binary, … }   # changing this also triggers the post\n```" + `



Scenario-level post and cue-level posts are pooled together before deduplication, so identical commands across both levels still run exactly once.



### Service shorthands

` + "```yaml\npost: restart:saver   # expands to the service's restart command\npost: reload:nginx    # expands to the service's reload command\n```" + `

` + "Shorthands scan all scenarios for a service cue (" + `nature: service` + ") whose " + `name:` + " matches, call " + `manager.ExpandCommands` + ", and inherit the service cue's " + `sudo:` + " flag. Expanded before deduplication. " + `deploy:<name>` + " is also supported (runs " + `systemctl daemon-reload && systemctl enable <name>` + " for systemd)." + `

### Service command overrides

` + "`commands:`" + ` overrides or adds actions for any service. Template variables: ` + "`{name}`" + `, ` + "`{binary}`" + `, ` + "`{dir}`" + `, ` + "`{service_file}`" + `. Action references ` + "`{start}`" + `, ` + "`{stop}`" + `, ` + "`{restart}`" + `, ` + "`{reload}`" + ` etc. expand to the **pre-override** base command, enabling a call-super pattern:

` + "```yaml\nMyScenario:\n  cues:\n    - name: nginx-front   # infers nature: service from manager:\n      manager: systemd\n      sudo: true\n      commands:\n        reload: nginx -t && {reload}   # test config, then run original systemctl reload nginx-front\n```" + `

### requires vs inline scenario refs

Two mechanisms for scenario composition — choose consciously:

| | ` + "`requires:`" + ` | inline ` + "`{ scenario: x }`" + ` in ` + "`cues:`" + ` |
|---|---|---|
| Deduplication | yes — each scenario runs once even if required by many | no — expands at the call-site position each time |
| Ordering | all prerequisites complete before parent starts | cues interleave at the exact position in the list |
| ` + "`on_error`" + ` scope | each scenario is independent — parent's restore does not cover it | parent's ` + "`on_error`" + ` applies — a failure in an inlined cue triggers the composing scenario's rollback |
| Use when | "these must finish first; they own their error handling" | "these cues are part of me; restore everything together" |

` + "```yaml\n# requires: — files deploy independently, before deploy starts.\n# If app fails, app's on_error applies (default: halt). deploy's rollback never fires.\ndeploy:\n  requires: [app, config]\n  on_error: restore   # only covers deploy's own cues\n  cues:\n    - name: migrate ...\n\n# inline ref — files are part of deploy. If app's pack cue fails,\n# deploy's on_error: restore fires and rolls back everything.\ndeploy:\n  on_error: restore\n  cues:\n    - { scenario: app }    # expanded inline; parent's on_error covers this\n    - { scenario: config }\n    - name: migrate ...\n```" + `

Narrowing: ` + "`{ scenario: app, cue: source }`" + ` runs only the named cue; ` + "`{ scenario: app, cues: [source, env] }`" + ` runs a subset. Nested refs are supported.`

const sectionMixedDeploys = `
These scenarios arise whenever files reach the target outside of a normal ` + "`regis run`" + ` — emergency
hotfixes, manual uploads, a partial deploy that failed mid-way, or a first-time bootstrap.
The deployment state (` + "`.regis-state`" + ` in ` + "`target.dir`" + `) may then be missing, incomplete, or describe
a different set of files than what is actually on the target.

**Why it matters** — rdiff uses the manifest's recorded hashes for fast drift detection. A stale
manifest causes false drift alerts or hides real ones. Rollback restores files from the remote
archive, which is consistent with the manifest at archive time; a rebuild creates a new archive
from the current target state so future rollbacks land in a known-good place.

#### Diagnosis — ` + "`state check`" + `

` + "```" + `
regis state check          # compare live manifest hashes against actual remote files
regis state check v20260601-120000  # compare a historical manifest instead
` + "```" + `

Output per cue:
` + "```" + `
  =  hash matches
  ~  hash differs (drift or partial deploy)
  ?  file exists on target but not tracked in manifest
  *  render file — exists, hash not recorded by manifest
  -  dest missing on target
` + "```" + `

#### Remediation options

**1. Rebuild the manifest** (recommended when target files are correct but manifest is stale):
` + "```" + `
regis state check --rebuild
` + "```" + `
Hashes every tracked remote file, writes a new manifest with a fresh state ID, creates a local
snapshot, and archives the current target state. Future ` + "`rollback`" + ` will restore this state.
**Best-effort**: hashes reflect remote files at check time. If local sources diverge from target,
run ` + "`regis run`" + ` for a guaranteed accurate manifest.

**2. Remove the manifest** (clean slate, next ` + "`regis run`" + ` creates a fresh one):
` + "```" + `
regis state check --remove
` + "```" + `

**3. Force-manifest on next run** (all files already correct, just need a manifest):
` + "```" + `
regis run --force-manifest
` + "```" + `
Writes a manifest even when nothing changed (all StatusEqual). Hashes binary files from
` + "`r.LocalHash`" + `; single-src config/secret from ` + "`Src[0]`" + `; multi-src config is skipped (no single
representative hash). Use ` + "`state check --rebuild`" + ` if you need config/secret hashes too.

**4. Fresh deploy** (wipe target and redeploy from scratch — forces all StatusChanged):
` + "```" + `
regis run --fresh [scenario]
` + "```" + `
Creates a timestamped tar.gz backup next to ` + "`target.dir`" + ` on the remote, wipes all contents, then
runs the normal deploy. Because every cue is ` + "`StatusChanged`" + `, the manifest is written with full
hashes. Prompts for confirmation unless ` + "`--yes`" + ` is set. Backup path:
` + "`<parent_of_target_dir>/<basename>-bak-<timestamp>.tar.gz`" + `.

#### Release history after remediation

All remediation paths (rebuild, force-manifest, fresh) generate a **new state ID** and append it
to the archive — they do not rewrite history. After a rebuild following a partial deploy:

` + "```" + `
v20260612-143022  ← rebuilt checkpoint (rollback target)
v20260601-120000  ← partial/broken release (stays in history)
` + "```" + `

` + "`release rollback`" + ` with no args picks the entry before the latest, so it naturally lands on the
rebuild checkpoint, skipping the broken release.
`

// generate writes the AI context document to outFile, sourcing data from the

// provided paths. All paths may be absolute or relative to the process cwd.

func generate(typesFile, cueDir, interpolateFile, cmdDir, exampleFile, outFile string) error {

	// 1. Parse types.go for schema tables

	schemaSection, err := buildSchemaSection(typesFile)

	if err != nil {

		return err

	}



	// 2. Parse cue files for nature types

	natureSection := buildNatureSection(cueDir)



	// 3. Parse interpolate.go for interpolation doc

	interpolSection, err := buildInterpolSection(interpolateFile)

	if err != nil {

		return err

	}



	// 4. Parse cobra commands for CLI reference

	cliSection := buildCLISection(cmdDir)



	// 5. Read the example YAML from the given path

	exampleData, err := os.ReadFile(exampleFile)

	if err != nil {

		return fmt.Errorf("regis-docgen: read %s: %w", exampleFile, err)

	}



	// 6. Assemble the full output

	var out bytes.Buffer

	out.WriteString(docgenHeader)



	out.WriteString("## Schema Reference\n\n")

	out.WriteString(schemaSection)



	out.WriteString("## Nature Types\n\n")

	out.WriteString(natureSection)



	out.WriteString("## Interpolation\n\n")

	out.WriteString(interpolSection)



	out.WriteString("## Key Concepts\n")

	out.WriteString(sectionKeyConceptsBody)

	out.WriteString("\n\n---\n\n")

	out.WriteString("## Mixed regis + manual deployments\n")

	out.WriteString(sectionMixedDeploys)

	out.WriteString("\n\n---\n\n")

	out.WriteString("## CLI Reference\n\n")

	out.WriteString(cliSection)



	out.WriteString("## Example regis.yml\n\n")

	out.WriteString("```yaml\n")

	out.Write(exampleData)

	out.WriteString("```\n")



	if err := os.WriteFile(outFile, out.Bytes(), 0644); err != nil {

		return fmt.Errorf("regis-docgen: write %s: %w", outFile, err)

	}



	fmt.Printf("regis-docgen: wrote %s\n", outFile)

	return nil

}



// generateSchema writes a dense annotated YAML schema to outFile.
func generateSchema(typesFile, outFile string) error {
	content, err := buildDenseSchema(typesFile)
	if err != nil {
		return err
	}
	if err := os.WriteFile(outFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("regis-docgen: write %s: %w", outFile, err)
	}
	fmt.Printf("regis-docgen: wrote %s\n", outFile)
	return nil
}

// buildDenseSchema generates a dense annotated YAML schema reference.
// Values are real/default values; options and mandatory appear only in comments.
func buildDenseSchema(typesFile string) (string, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, typesFile, nil, parser.ParseComments)
	if err != nil {
		return "", fmt.Errorf("regis-docgen: parse %s: %w", typesFile, err)
	}
	s := extractStructs(f)

	var b bytes.Buffer

	// fl writes one aligned YAML field line with an inline comment.
	fl := func(indent, key, val, comment string) {
		kv := indent + key + ": " + val
		if comment != "" {
			fmt.Fprintf(&b, "%-44s  # %s\n", kv, comment)
		} else {
			fmt.Fprintf(&b, "%s\n", kv)
		}
	}

	b.WriteString("# regis.yml schema — auto-generated by regis-docgen, do not edit\n")
	b.WriteString("# mandatory fields are marked in comments\n\n")

	// targets
	b.WriteString("targets:\n")
	reqTarget := map[string]bool{"name": true, "host": true}
	for i, fi := range s["Target"] {
		pfx := "    "
		if i == 0 {
			pfx = "  - "
		}
		fl(pfx, fi.yamlKey, schemaVal(fi, reqTarget[fi.yamlKey]), schemaComment(fi, reqTarget[fi.yamlKey]))
	}
	b.WriteString("\n")

	// defaults — show env as an example key-value block
	b.WriteString("defaults:\n")
	for _, fi := range s["DefaultsConfig"] {
		if fi.yamlKey == "env" {
			fmt.Fprintf(&b, "%-44s  # %s\n", "  env:", schemaComment(fi, false))
			b.WriteString("    APP_ENV: production\n")
			b.WriteString("    LOG_LEVEL: info\n")
		} else {
			fl("  ", fi.yamlKey, schemaVal(fi, false), schemaComment(fi, false))
		}
	}
	b.WriteString("\n")

	// scenarios
	b.WriteString("scenarios:\n")
	b.WriteString("  <name>:\n")
	for _, fi := range s["Scenario"] {
		switch fi.yamlKey {
		case "cues", "checks", "rollback":
			continue // expanded below
		}
		fl("    ", fi.yamlKey, schemaVal(fi, false), schemaComment(fi, false))
	}
	// cues list
	b.WriteString("    cues:\n")
	cueReq := map[string]bool{"name": true, "nature": true}
	for i, fi := range s["CueRef"] {
		pfx := "        "
		if i == 0 {
			pfx = "      - "
		}
		switch fi.yamlKey {
		case "src":
			b.WriteString("        # ── file upload: binary/secret = single file · config = multi-file/glob/tree · pack = glob tree with prune · or use git: true instead of src for pack ──\n")
		case "shell":
			b.WriteString("        # ── action / generate ──\n")
		case "post":
			b.WriteString("        # ── common remote cue fields (binary · config · secret · pack · service · render) ──\n")
	case "diff_mode":
			b.WriteString("        # ── pack / config / render: diff control ──\n")
		case "prune":
			b.WriteString("        # ── pack / render folder mode ──\n")
		case "manager":
			b.WriteString("        # ── service (manager: present infers nature: service) ──\n")
		case "restore":
			b.WriteString("        # ── per-cue rollback (infers on_error: restore; true/\"cmd\"/{shell,sudo}/defer) ──\n")
		}
		fl(pfx, fi.yamlKey, schemaVal(fi, cueReq[fi.yamlKey]), schemaComment(fi, cueReq[fi.yamlKey]))
	}
	// checks list — same structure as cues but read-only probes
	b.WriteString("    checks:                  # terminal acceptance probes; run after cues complete\n")
	b.WriteString("      - name: <string>       # required\n")
	b.WriteString("        nature: action       # checks are read-only action cues\n")
	b.WriteString("        shell: <string>      # probe command\n")
	// rollback list — actions run on remote after file-snapshot restore
	b.WriteString("    rollback:                # actions run on remote after snapshot restore when on_error: restore\n")
	b.WriteString("      - name: <string>       # required\n")
	b.WriteString("        shell: <string>      # remote command; $RELEASE_ID is available\n")
	b.WriteString("        sudo: false\n")
	b.WriteString("\n")

	// run
	b.WriteString("run:\n")
	for _, fi := range s["RunConfig"] {
		fl("  ", fi.yamlKey, schemaVal(fi, false), schemaComment(fi, false))
	}
	b.WriteString("\n")

	// release — show dir with a concrete example path
	b.WriteString("release:\n")
	for _, fi := range s["ReleaseConfig"] {
		val := schemaVal(fi, false)
		if fi.yamlKey == "dir" {
			val = "/opt/app/.regis-releases" // representative example
		}
		fl("  ", fi.yamlKey, val, schemaComment(fi, false))
	}
	b.WriteString("\n")

	// concurrency
	if len(s["ConcurrencyConfig"]) > 0 {
		b.WriteString("concurrency:\n")
		for _, fi := range s["ConcurrencyConfig"] {
			fl("  ", fi.yamlKey, schemaVal(fi, false), schemaComment(fi, false))
		}
		b.WriteString("\n")
	}

	// pre / post: run before/after all cues; local: true = local machine, default = SSH target
	b.WriteString("pre:\n")
	b.WriteString(fmt.Sprintf("%-44s  # runs on target via SSH before any cue\n", "  - cmd: \"systemctl stop watchdog\""))
	b.WriteString(fmt.Sprintf("%-44s  # runs on local machine (notify, build, etc.)\n", "  - cmd: \"curl -s https://hooks/deploy-start\""))
	b.WriteString(fmt.Sprintf("%-44s\n", "    local: true"))
	b.WriteString("\n")
	b.WriteString("post:\n")
	b.WriteString(fmt.Sprintf("%-44s  # runs on target via SSH after all cues succeed\n", "  - cmd: \"systemctl start watchdog\""))
	b.WriteString(fmt.Sprintf("%-44s  # runs on local machine after deploy\n", "  - cmd: \"curl -s https://hooks/deploy-done\""))
	b.WriteString(fmt.Sprintf("%-44s\n", "    local: true"))
	b.WriteString("\n")

	return b.String(), nil
}

// schemaVal returns the actual/default YAML value for a field.
// mandatory fields with alternatives show the first alternative as an example value.
func schemaVal(fi fieldInfo, mandatory bool) string {
	alts := schemaExtractAlts(fi.doc)
	def := fi.def

	if mandatory {
		// Show first alternative as example (e.g. "binary" for nature), else empty
		if len(alts) > 0 {
			return alts[0]
		}
		return `""`
	}

	switch fi.goType {
	case "bool":
		if def == "true" {
			return "true"
		}
		return "false"
	case "int":
		if def != "" {
			return def
		}
		return "0"
	case "map":
		return "{}"
	case "string or []string":
		return "[]"
	case "string or object":
		return `""`
	case "[]cue":
		return "[]"
	default: // string
		if def != "" {
			return def
		}
		if len(alts) > 0 {
			return alts[0] // first option as example
		}
		return `""`
	}
}

// schemaComment builds the inline comment: "mandatory — opts — short doc"
// or "opts — short doc" or just short doc.
func schemaComment(fi fieldInfo, mandatory bool) string {
	alts := schemaExtractAlts(fi.doc)
	short := schemaShortDoc(fi.doc)

	var parts []string
	if mandatory {
		parts = append(parts, "mandatory")
	}
	if len(alts) > 0 {
		parts = append(parts, strings.Join(alts, "|"))
	}
	if short != "" {
		parts = append(parts, short)
	}
	return strings.Join(parts, " — ")
}

// schemaShortDoc strips alternatives and default hints from a doc string,
// leaving only the human description.
func schemaShortDoc(doc string) string {
	// Strip " (default: x)" suffix
	if i := strings.Index(doc, " (default:"); i >= 0 {
		doc = doc[:i]
	}
	// "description: opt1 | opt2" → strip ": opt1 | opt2"
	if i := strings.LastIndex(doc, ": "); i >= 0 {
		if strings.Contains(doc[i+2:], " | ") {
			doc = strings.TrimSpace(doc[:i])
		}
	}
	// "opt1 | opt2 — description" → take text after " — "
	if i := strings.Index(doc, " \u2014 "); i >= 0 {
		if strings.Contains(doc[:i], " | ") {
			doc = strings.TrimSpace(doc[i+4:])
		}
	}
	return doc
}

// schemaExtractAlts parses "opt1 | opt2 | opt3" patterns from a doc string.
// Returns nil when no clean alternatives list is found.
func schemaExtractAlts(doc string) []string {
	if !strings.Contains(doc, " | ") {
		return nil
	}
	s := doc
	// Strip "(default: x)" suffix
	if i := strings.Index(s, " (default:"); i >= 0 {
		s = s[:i]
	}
	// Strip " — description" suffix (em dash: U+2014); alternatives are before it
	if i := strings.Index(s, " \u2014 "); i >= 0 {
		s = s[:i]
	}
	// If pattern is "description: opt1 | opt2", take only the opts part
	if i := strings.LastIndex(s, ": "); i >= 0 {
		candidate := s[i+2:]
		if strings.Contains(candidate, " | ") {
			s = candidate
		}
	}
	parts := strings.Split(s, " | ")
	var result []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		// Skip parts that look like prose (contain punctuation or are long)
		if p == "" || len(p) > 20 || strings.ContainsAny(p, ".,;()") {
			return nil
		}
		result = append(result, p)
	}
	if len(result) < 2 {
		return nil
	}
	return result
}

func main() {

	if err := generate(

		defaultTypesFile,

		defaultCueDir,

		defaultInterpolFile,

		defaultCobraDir,

		defaultExampleFile,

		defaultContextFile,

	); err != nil {

		fmt.Fprintln(os.Stderr, err)

		os.Exit(1)

	}

	if err := generateSchema(
		defaultTypesFile,
		defaultSchemaFile,
	); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}



// buildSchemaSection returns the ## Schema Reference body (tables from types.go).

func buildSchemaSection(typesFile string) (string, error) {

	fset := token.NewFileSet()

	f, err := parser.ParseFile(fset, typesFile, nil, parser.ParseComments)

	if err != nil {

		return "", fmt.Errorf("regis-docgen: parse %s: %w", typesFile, err)

	}



	structs := extractStructs(f)



	var buf bytes.Buffer



	// targets[]

	buf.WriteString("### targets[]\n\n")

	buf.WriteString("| field | type | default | description |\n")

	buf.WriteString("|-------|------|---------|-------------|\n")

	for _, fi := range structs["Target"] {

		buf.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n",

			fi.yamlKey, fi.goType, dashOrBacktick(fi.def), fi.doc))

	}

	buf.WriteString("\nThe first target is used by default. `--target <name>` selects by name.\n")

	buf.WriteString("\n---\n\n")



	// scenarios{}

	buf.WriteString("### scenarios{}\n\n")

	buf.WriteString("| field | type | description |\n")

	buf.WriteString("|-------|------|-------------|\n")

	for _, fi := range structs["Scenario"] {

		buf.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n",

			fi.yamlKey, fi.goType, fi.doc))

	}

	buf.WriteString("\n---\n\n")



	// cues[]

	buf.WriteString("### cues[]\n\n")

	buf.WriteString("| field | required | description |\n")

	buf.WriteString("|-------|----------|-------------|\n")

	for _, fi := range structs["CueRef"] {

		required := "no"

		if fi.yamlKey == "name" || fi.yamlKey == "nature" {

			required = "yes"

		}

		buf.WriteString(fmt.Sprintf("| `%s` | %s | %s |\n",

			fi.yamlKey, required, fi.doc))

	}

	buf.WriteString("\n**Composite cue reference fields** (used instead of `name`/`nature`):\n\n")

	buf.WriteString("| field | description |\n")

	buf.WriteString("|-------|-------------|\n")

	buf.WriteString("| `scenario` | Reference another scenario — all its cues run inline at this position |\n")

	buf.WriteString("| `cue` | Narrow a scenario reference to a single named cue |\n")

	buf.WriteString("| `cues` | Narrow a scenario reference to a subset of named cues (list) |\n")

	buf.WriteString("\n---\n\n")



	// service cues (inline — fields already in cues[] table, just add a note)

	buf.WriteString("### service cues (nature: service)\n\n")

	buf.WriteString("Service metadata lives inline in the cue list. Setting `manager:` infers `nature: service`.\n\n")

	buf.WriteString("Built-in managers (`systemd`, `crontab`) provide default commands automatically. Any other manager string requires `commands:` to be declared.\n\n")

	buf.WriteString("Command templates support `{name}`, `{binary}`, `{dir}`, `{service_file}` substitutions, plus `{start}`, `{stop}`, `{restart}`, `{reload}` etc. which expand to the pre-override base command (call-super: `nginx -t && {reload}`).\n\n")

	buf.WriteString("The `deploy:<name>` shorthand triggers `systemctl daemon-reload && systemctl enable <name>` (systemd) or the crontab install command. It is queued automatically when a `service_file` is uploaded.\n")

	buf.WriteString("\n---\n\n")



	// run

	buf.WriteString("### run\n\n")

	buf.WriteString("| field | type | default | description |\n")

	buf.WriteString("|-------|------|---------|-------------|\n")

	for _, fi := range structs["RunConfig"] {

		buf.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n",

			fi.yamlKey, fi.goType, dashOrBacktick(fi.def), fi.doc))

	}

	buf.WriteString("\n`run.success_when: auto` resolves: checks exist → `checks`; service action ran → `service`; otherwise → `command`.\n")

	buf.WriteString("\n---\n\n")



	// release

	buf.WriteString("### release\n\n")

	buf.WriteString("| field | type | default | description |\n")

	buf.WriteString("|-------|------|---------|-------------|\n")

	for _, fi := range structs["ReleaseConfig"] {

		buf.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s |\n",

			fi.yamlKey, fi.goType, dashOrBacktick(fi.def), fi.doc))

	}

	buf.WriteString("\n`release.enabled: true` (default) — assigns a state ID per deploy, archives files locally and remotely for rollback. Set to `false` for live deploys with no history.\n")

	buf.WriteString("\n---\n\n")

	buf.WriteString("### Rollback\n\n")

	buf.WriteString("When `on_error: restore` triggers (explicit or inferred from per-cue `rollback:` fields), a deploy failure runs rollback in four steps:\n\n")
	buf.WriteString("1. Find the most recent local release snapshot (`.regis-releases/<prevID>/`).\n")
	buf.WriteString("2. **Per-cue compensations** — execute in full **reverse execution order** for every cue where `rollback:` is enabled:\n")
	buf.WriteString("   - File natures (binary/config/secret/render/pack): re-upload the previous snapshot's files for that cue to their recorded remote paths.\n")
	buf.WriteString("   - Action natures: run the `rollback: \"shell cmd\"` command on the remote.\n")
	buf.WriteString("3. If no per-cue `rollback:` was declared (legacy / explicit `on_error: restore`): re-upload **all** artifacts from the previous snapshot.\n")
	buf.WriteString("4. **Scenario-level rollback block** — the `rollback:` cue list under each scenario runs in topo order.\n\n")

	buf.WriteString("**Inferred `on_error: restore`**: if any direct cue in a scenario declares `rollback: true` or `rollback: \"cmd\"`, the runner automatically treats that scenario as `on_error: restore` — no explicit setting needed.\n\n")

	buf.WriteString("**Per-cue rollback syntax** (on any cue in `cues:`):\n\n")
	buf.WriteString("```yaml\n# File natures — restore from previous snapshot\n- name: frontend\n  nature: pack\n  src: dist/**\n  dest: ./\n  rollback: true          # restores all pack files from previous snapshot\n\n# Action natures — run a compensation command\n- name: go-offline\n  shell: touch maintenance.flag\n  rollback: \"rm -f maintenance.flag\"   # undo: remove the flag\n\n# Or with sudo:\n- name: deploy-service\n  shell: systemctl start myapp\n  rollback:\n    shell: systemctl stop myapp\n    sudo: true\n\n# rollback: defer — re-run this cue's shell AFTER all per-cue file restores complete.\n# Use when the command must reconcile with restored files (e.g. dependency install).\n- name: install-deps\n  shell: composer install\n  rollback: defer         # skipped in reverse phase; re-run after vendor/ is restored\n```\n\n")

	buf.WriteString("`$RELEASE_ID` is injected into the env of every cue and every rollback action at deploy start, so pre-deploy backup labels and rollback restore labels match:\n\n")

	buf.WriteString("```yaml\nDeploy:\n  rollback:                      # scenario-level: runs after per-cue compensations\n    - name: restore-db\n      shell: php artisan db:restore --label=pre-${RELEASE_ID}\n  cues:\n    - name: backup-db\n      shell: php artisan db:backup --label=pre-${RELEASE_ID}\n      # no rollback: — backup can't be undone, just skip\n    - name: go-offline\n      shell: touch maintenance.flag\n      rollback: \"rm -f maintenance.flag\"\n    - name: frontend\n      nature: pack\n      src: dist/**\n      dest: /var/www/\n      rollback: true               # file restore from previous snapshot\n    - name: go-online\n      shell: rm -f maintenance.flag\n      rollback: \"touch maintenance.flag\"   # reverse: put back into maintenance\n```\n\n")

	buf.WriteString("Rollback requires `release.enabled: true` (default) so a local snapshot exists. If no previous release is found, rollback runs compensations that have `shell:` but skips file restore. Pack snapshots are included automatically when `rollback: true` is set.\n")

	buf.WriteString("\n---\n\n")

	buf.WriteString("### Pack prune\n\n")

	buf.WriteString("`nature: pack` defaults to `prune: true` — safe because tier 1 uses the managed manifest (exact diff, only regis-managed files removed). Set `prune: false` to disable. Three-tier resolution:\n\n")

	buf.WriteString("| Tier | Condition | Behaviour |\n")
	buf.WriteString("|------|-----------|----------|\n")
	buf.WriteString("| 1 | `.regis-pack-<name>` manifest in dest (or release archive) | Exact diff — only previously-managed files removed. Automatic. |\n")
	buf.WriteString("| 2 | No manifest; flat src patterns (e.g. `*.html`) | Scope-filtered candidates shown with mtime; auto-prune with `-y`. |\n")
	buf.WriteString("| 3 | No manifest; no flat patterns | Lists unmanaged files as informational; no deletion. |\n\n")

	buf.WriteString("The managed manifest (`.regis-pack-<name>`) is **always written** after a successful deploy, even when `prune: false`, so tier 1 is ready on the next run.\n")

	buf.WriteString("\n---\n\n")

	return buf.String(), nil

}



// buildNatureSection parses internal/cue/*.go for // doc:nature blocks.

func buildNatureSection(cueDir string) string {

	cueFiles, err := filepath.Glob(filepath.Join(cueDir, "*.go"))

	if err != nil || len(cueFiles) == 0 {

		return ""

	}



	var entries []natureEntry



	for _, path := range cueFiles {

		data, err := os.ReadFile(path)

		if err != nil {

			continue

		}

		lines := strings.Split(string(data), "\n")



		var natureName string

		var docLines []string



		for _, line := range lines {

			line = strings.TrimRight(line, "\r")

			stripped := strings.TrimPrefix(line, "// ")

			stripped = strings.TrimPrefix(stripped, "//")



			if strings.HasPrefix(stripped, "doc:nature ") {

				natureName = strings.TrimPrefix(stripped, "doc:nature ")

				natureName = strings.TrimSpace(natureName)

				docLines = nil

				continue

			}



			if natureName != "" {

				if strings.HasPrefix(line, "//") {

					docLines = append(docLines, strings.TrimSpace(stripped))

				} else {

					// End of comment block

					entries = append(entries, natureEntry{name: natureName, lines: docLines})

					natureName = ""

					docLines = nil

				}

			}

		}

		// flush if file ended while in a block

		if natureName != "" {

			entries = append(entries, natureEntry{name: natureName, lines: docLines})

		}

	}



	// Sort by nature name for stable output

	sort.Slice(entries, func(i, j int) bool {

		return entries[i].name < entries[j].name

	})



	var buf bytes.Buffer

	for _, e := range entries {

		buf.WriteString(fmt.Sprintf("### %s\n\n", e.name))

		for _, l := range e.lines {

			if l != "" {

				buf.WriteString(l + "\n")

			}

		}

		buf.WriteString("\n")

	}

	buf.WriteString("---\n\n")

	return buf.String()

}



// buildInterpolSection parses internal/config/interpolate.go for the // doc:interpolation block.

func buildInterpolSection(interpolFile string) (string, error) {

	data, err := os.ReadFile(interpolFile)

	if err != nil {

		return "", fmt.Errorf("regis-docgen: read %s: %w", interpolFile, err)

	}



	lines := strings.Split(string(data), "\n")

	var docLines []string

	inBlock := false



	for _, line := range lines {

		line = strings.TrimRight(line, "\r")

		stripped := strings.TrimPrefix(line, "// ")

		stripped = strings.TrimPrefix(stripped, "//")



		if strings.TrimSpace(stripped) == "doc:interpolation" {

			inBlock = true

			continue

		}



		if inBlock {

			if strings.HasPrefix(line, "//") {

				docLines = append(docLines, strings.TrimSpace(stripped))

			} else {

				break

			}

		}

	}



	var buf bytes.Buffer

	for _, l := range docLines {

		buf.WriteString(l + "\n")

	}

	buf.WriteString("\n---\n\n")

	return buf.String(), nil

}



// cobraCmd holds a parsed cobra.Command Use + Short pair.

type cobraCmd struct {

	use   string

	short string

}



// buildCLISection parses cmd/regis/cmd/*.go for cobra.Command Use+Short fields.

func buildCLISection(cobraDir string) string {

	goFiles, err := filepath.Glob(filepath.Join(cobraDir, "*.go"))

	if err != nil || len(goFiles) == 0 {

		return ""

	}



	fset := token.NewFileSet()

	var cmds []cobraCmd



	for _, path := range goFiles {

		// Skip test files

		if strings.HasSuffix(path, "_test.go") {

			continue

		}

		f, err := parser.ParseFile(fset, path, nil, 0)

		if err != nil {

			continue

		}

		found := extractCobraCommands(f)

		cmds = append(cmds, found...)

	}



	// Deduplicate by Use

	seen := make(map[string]bool)

	var unique []cobraCmd

	for _, c := range cmds {

		if !seen[c.use] {

			seen[c.use] = true

			unique = append(unique, c)

		}

	}



	// Filter: skip subcommand verbs (service subcommands like "start <name>", release subcommands)

	// and skip the root command "regis" itself.

	skipVerbs := map[string]bool{

		"start": true, "stop": true, "restart": true, "reload": true,

		"enable": true, "disable": true, "logs": true,

		"list": true, "current": true, "restore": true,

		"regis": true, // root command

	}

	var topLevel []cobraCmd

	for _, c := range unique {

		firstWord := strings.Fields(c.use)[0]

		if skipVerbs[firstWord] {

			continue

		}

		topLevel = append(topLevel, c)

	}



	// Sort by Use for stable output

	sort.Slice(topLevel, func(i, j int) bool {

		return topLevel[i].use < topLevel[j].use

	})



	var buf bytes.Buffer



	buf.WriteString("### Global flags\n\n")

	buf.WriteString("| flag | short | description |\n")

	buf.WriteString("|------|-------|-------------|\n")

	buf.WriteString("| `--file` | `-f` | config file (default: regis.yml) |\n")

	buf.WriteString("| `--target` | | target selector: name, comma-list, `all`, or glob |\n")

	buf.WriteString("| `--dry-run` | `-n` | show what would happen without executing |\n")

	buf.WriteString("| `--run-without-check` | | deploy without rdiff preview (CI/automation) |\n")
	buf.WriteString("| `--allow-dirty` | | allow rdiff and deploy with uncommitted changes |\n")
	buf.WriteString("| `--no-git` | | allow rdiff and deploy without a git repository |\n")

	buf.WriteString("| `--verbose` | `-v` | show unchanged cues and full command output |\n")

	buf.WriteString("| `--quiet` | `-q` | errors and summary only |\n")

	buf.WriteString("| `--plain` | | force plain output (level 1) |\n")

	buf.WriteString("| `--nature` | `-N` | filter cues by nature: binary,config,secret,action,generate,render |\n")

	buf.WriteString("\n---\n\n")



	buf.WriteString("### Commands\n\n")

	buf.WriteString("| command | description |\n")

	buf.WriteString("|---------|-------------|\n")

	for _, c := range topLevel {

		buf.WriteString(fmt.Sprintf("| `regis %s` | %s |\n", c.use, c.short))

	}

	buf.WriteString("\n---\n\n")



	return buf.String()

}



// extractCobraCommands walks the AST and returns Use+Short from cobra.Command literals.

func extractCobraCommands(f *ast.File) []cobraCmd {

	var results []cobraCmd



	ast.Inspect(f, func(n ast.Node) bool {

		lit, ok := n.(*ast.CompositeLit)

		if !ok {

			return true

		}



		// Check if this is a cobra.Command literal

		sel, ok := lit.Type.(*ast.SelectorExpr)

		if !ok {

			return true

		}

		pkg, ok := sel.X.(*ast.Ident)

		if !ok || pkg.Name != "cobra" || sel.Sel.Name != "Command" {

			return true

		}



		var use, short string

		for _, elt := range lit.Elts {

			kv, ok := elt.(*ast.KeyValueExpr)

			if !ok {

				continue

			}

			key, ok := kv.Key.(*ast.Ident)

			if !ok {

				continue

			}

			val, ok := kv.Value.(*ast.BasicLit)

			if !ok || val.Kind != token.STRING {

				continue

			}

			// val.Value is a Go string literal; strip surrounding quotes/backticks

			strVal := val.Value

			if len(strVal) >= 2 {

				if (strVal[0] == '"' && strVal[len(strVal)-1] == '"') ||

					(strVal[0] == '`' && strVal[len(strVal)-1] == '`') {

					strVal = strVal[1 : len(strVal)-1]

				}

			}

			switch key.Name {

			case "Use":

				use = strVal

			case "Short":

				short = strVal

			}

		}



		if use != "" && short != "" {

			results = append(results, cobraCmd{use: use, short: short})

		}



		return true

	})



	return results

}



// extractStructs returns a map of struct name -> ordered []fieldInfo,

// only for fields that have a // doc: comment.

func extractStructs(f *ast.File) map[string][]fieldInfo {

	result := make(map[string][]fieldInfo)



	for _, decl := range f.Decls {

		genDecl, ok := decl.(*ast.GenDecl)

		if !ok || genDecl.Tok != token.TYPE {

			continue

		}

		for _, spec := range genDecl.Specs {

			typeSpec, ok := spec.(*ast.TypeSpec)

			if !ok {

				continue

			}

			structType, ok := typeSpec.Type.(*ast.StructType)

			if !ok {

				continue

			}

			structName := typeSpec.Name.Name

			var fields []fieldInfo

			for _, field := range structType.Fields.List {

				if len(field.Names) == 0 {

					continue

				}

				doc := extractDocComment(field.Comment)

				if doc == "" {

					doc = extractDocComment(field.Doc)

				}

				if doc == "" {

					continue

				}



				fieldName := field.Names[0].Name

				yamlKey := yamlTagKey(field.Tag, fieldName)

				if yamlKey == "-" {

					continue

				}



				goTyp := simplifyType(field.Type)

				def := defaults[structName+"."+fieldName]



				fields = append(fields, fieldInfo{

					yamlKey: yamlKey,

					goType:  goTyp,

					doc:     doc,

					def:     def,

				})

			}

			if len(fields) > 0 {

				result[structName] = fields

			}

		}

	}

	return result

}



// extractDocComment extracts text after "// doc: " from a comment group.

func extractDocComment(cg *ast.CommentGroup) string {

	if cg == nil {

		return ""

	}

	for _, c := range cg.List {

		text := c.Text

		const prefix = "// doc: "

		if idx := strings.Index(text, prefix); idx >= 0 {

			return strings.TrimSpace(text[idx+len(prefix):])

		}

	}

	return ""

}



// yamlTagKey extracts the yaml key from a struct tag, or falls back to

// converting the field name to snake_case.

func yamlTagKey(tag *ast.BasicLit, fieldName string) string {

	if tag != nil {

		raw := tag.Value

		// strip surrounding backticks

		raw = strings.Trim(raw, "`")

		st := reflect.StructTag(raw)

		val := st.Get("yaml")

		if val != "" {

			key := strings.Split(val, ",")[0]

			if key == "-" {

				return "-"

			}

			if key != "" {

				return key

			}

		}

	}

	return toSnakeCase(fieldName)

}



// toSnakeCase converts CamelCase to snake_case.

func toSnakeCase(s string) string {

	var b strings.Builder

	for i, r := range s {

		if unicode.IsUpper(r) && i > 0 {

			b.WriteByte('_')

		}

		b.WriteRune(unicode.ToLower(r))

	}

	return b.String()

}



// simplifyType converts ast.Expr to a human-readable type string.

func simplifyType(expr ast.Expr) string {

	switch t := expr.(type) {

	case *ast.Ident:

		switch t.Name {

		case "string":

			return "string"

		case "int":

			return "int"

		case "bool":

			return "bool"

		case "StringOrList":

			return "string or []string"

		case "PostAction":

			return "string or object"

		case "WhenExpr":

			return "string or object"

		default:

			return t.Name

		}

	case *ast.ArrayType:

		inner := simplifyType(t.Elt)

		switch inner {

		case "CueRef":

			return "[]cue"

		default:

			return "[]" + inner

		}

	case *ast.MapType:

		return "map"

	case *ast.StarExpr:

		return simplifyType(t.X)

	default:

		return fmt.Sprintf("%T", expr)

	}

}



// dashOrBacktick returns "—" for empty defaults, or the value wrapped in backticks.

func dashOrBacktick(def string) string {

	if def == "" {

		return "—"

	}

	return "`" + def + "`"

}

